### ISSUE TITLE
提示找不到的消息 类型

### ISSUE THREAD

**Issue by Rekoe** [nonpool/typedispatchdemo#1]
```
Caused by: java.lang.RuntimeException: unknown Message type :TextMessage
	at com.nonpool.util.ParseFromUtil.parse(ParseFromUtil.java:48)
	at com.nonpool.server.handler.SecondProtobufCodec.decode(SecondProtobufCodec.java:28)
	at com.nonpool.server.handler.SecondProtobufCodec.decode(SecondProtobufCodec.java:1)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 25 more
```

**Comment by Rekoe** [comment]
通过debug 类``` List<Class> classes = ClassUtil.getAllClassBySubClass(MessageLite.class, true, "com.nonpool.proto");```
发现 classes 是空

**Comment by nonpool** [comment]
请问你是怎么运行的？ 我这边自己测试是没有问题的呢

**Comment by nonpool** [comment]
我找到问题了 我的ClassUtil在*nix系统下因为分隔符不同而导致无法正确扫描子类 已经修复 非常感谢你的反馈 详见[commit](https://github.com/nonpool/typedispatchdemo/commit/33869e4088d942e822838975abfba07db1191a57)

**Comment by Rekoe** [comment]
@nonpool 参照你的结构把国内的tio框架写了一个protobuf的版本
https://github.com/Rekoe/tio-game

**Comment by nonpool** [comment]
@Rekoe nice
